Body
alexa2me/PI-fluxo-de-login pull request #4
Opened 2022-08-31 00:05 UTC by arnoldcainan

2022-09-02 00:47 UTC, fernandagiacomel requested changes

2022-09-02 00:47 UTC, fernandagiacomel commented on index.html
> +        <footer>
Footer fica fora da tag main, ele seria na linha 34 após o fechamento da main

2022-09-02 00:47 UTC, fernandagiacomel commented on index.html
> +        <section>
em vez de section colocaria uma div. o melhor seria ter uma div container e dentro dela a div imagem e a div texto(o que esta dentro da section), para assim a gente usar flexbox

2022-09-03 19:39 UTC, alexa2me requested changes

2022-09-03 19:39 UTC, alexa2me commented on index.html
> +            <input type="email" placeholder="EMAIL">
O placeholder aqui é minúsculo (como no Figma):
`E-mail`

2022-09-03 19:39 UTC, alexa2me commented on index.html
> +            <input type="password" placeholder="SENHA">
O placeholder aqui é minúsculo (como no Figma):
`Senha`

2022-09-03 19:39 UTC, alexa2me commented on index.html
> +            <button type="button">Entrar</button>
Não é necessário o `type="button"`, pode remover.

2022-09-03 19:39 UTC, alexa2me commented on index.html
> +            <img src="./Img/img_tela_login2.jpg" alt="foto de background" >
O `alt` precisa descrever a imagem, senão quando o leitor de tela ler "foto de background" pode não ficar claro para quem está ouvindo.

2022-09-03 19:39 UTC, alexa2me commented on index.html
> +        <section>
@arnoldcainan, grid + flex dá certo aí, dá uma olhada aqui:
https://replit.com/@alexa2me/arnold-login#index.html

2022-09-03 19:39 UTC, alexa2me commented on style.css
> +}
@arnoldcainan dá uma olhada aqui:
https://replit.com/@alexa2me/arnold-login#style.css

2022-09-03 21:00 UTC, alexa2me commented
@arnoldcainan, nomeia a pasta de imagens como `images` (em inglês mesmo), pra ficar claro q serão algumas imagens (vai ter imagens do @harleiaki também)

2022-09-04 13:42 UTC, arnoldcainan commented on index.html
> +        <footer>
Alterado

2022-09-04 13:43 UTC, arnoldcainan commented on index.html
> +        <section>
Alterado

2022-09-04 13:44 UTC, arnoldcainan commented on index.html
> +            <input type="password" placeholder="SENHA">
Alterado

2022-09-04 13:45 UTC, arnoldcainan commented on index.html
> +            <button type="button">Entrar</button>
Alterado

2022-09-04 13:48 UTC, arnoldcainan commented on index.html
> +            <img src="./Img/img_tela_login2.jpg" alt="foto de background" >
Alterado

2022-09-04 19:09 UTC, fernandagiacomel reviewed
Revisei aqui e já ajustou tudo que foi apontado.

2022-09-07 23:24 UTC, fernandagiacomel approved these changes
Formatação ficou ok aqui nas minhas telas.

2022-09-07 23:43 UTC, arnoldcainan commented on index.html
> +            <input type="email" placeholder="EMAIL">
Alterado

2022-09-10 23:40 UTC, alexa2me approved these changes

2022-09-11 01:32 UTC, merged