Footer.harlei
alexa2me/PI-fluxo-de-login pull request #5
Opened 2022-08-31 20:46 UTC by harleiaki

Footer

2022-08-31 23:37 UTC, harleiaki commented
Footer

2022-09-02 00:40 UTC, fernandagiacomel requested changes

2022-09-02 00:40 UTC, fernandagiacomel commented on footer.html
> +        <p> Made with ♥ by &nbsp &nbsp &nbsp</p>
indentação: da linha 25 até 41 tem que estar dentro da tag div, então um tab a mais

2022-09-02 00:40 UTC, fernandagiacomel commented on footer.html
> +    </div>
indentação: linha 42 a </div> não pode estar alinhada com o footer, tem que estar pra dentro

2022-09-03 21:35 UTC, alexa2me requested changes
@harleiaki, cria uma pasta chamada `images` e coloca todas essas imagens dentro, o @arnoldcainan também tem imagens e vai fazer o mesmo.

2022-09-03 21:35 UTC, alexa2me commented on footer.css
> + .container{
@harleiaki, deixa mais específico de onde é esse container, tipo `.footer-container`

2022-09-03 21:35 UTC, alexa2me commented on footer.css
> +    width: 1440px;
O `width` você pode deixar com `100%`, assim o footer vai sempre ocupar 100% da largura da tela, se a dimensão diminuir, o footer acompanha.

2022-09-03 21:35 UTC, alexa2me commented on footer.css
> +    color: aliceblue;
A cor do texto é branca, #FFFFFF, precisa corrigir.

2022-09-03 21:35 UTC, alexa2me commented on footer.html
> +    <link href="footer.css" rel="stylesheet">
Vamos ter somente um arquivo de css, `style.css`, pra deixar o seu código de css separado, coloca `/* FOOTER */` no início do seu código de css. Pode renomear o `footer.css` para `style.css`.

2022-09-03 21:35 UTC, alexa2me commented on footer.html
> +
Remover espaço em branco.

2022-09-03 21:35 UTC, alexa2me commented on footer.html
> +
Remover todos os espaços em branco entre uma tag de `img` e outra.

2022-09-03 21:35 UTC, alexa2me commented on footer.html
> +
Remover espaço em branco depois da tag `</footer>`.

2022-09-03 23:36 UTC, closed without merging