Home não logado
alexa2me/PI-fluxo-de-login pull request #7
Opened 2022-09-01 14:18 UTC by marleicampos

2022-09-03 22:04 UTC, alexa2me requested changes

2022-09-03 22:04 UTC, alexa2me commented on reset.css
> +}
@marleicampos, não vamos precisar desse arquivo, vamos ter só um arquivo de css, o `style.css`, pode remover esse.

2022-09-03 22:04 UTC, alexa2me commented on index.html
> +        </div>
O seu arquivo de html e css é igual ao do @enricoasc, a diferença vai ser o que vai aparecer em `main` (outra pessoa está fazendo), dá uma olhada aqui:
https://replit.com/@alexa2me/enrico-header#index.html

O seu header é da tela `home`, o header do @enricoasc é da tela de `login`.
Muda o nome do seu arquivo para `home.html`.

2022-09-03 22:04 UTC, alexa2me commented on index.html
> +          <button type="button">Sair</button>
O texto do seu botão é `Entrar`, precisa corrigir.

2022-09-03 22:04 UTC, alexa2me commented on style.css
> +  height: 20px;
Pode usar o mesmo css que o @enricoasc, dá uma olhada aqui:
https://replit.com/@alexa2me/enrico-header#style.css

2022-09-04 19:12 UTC, fernandagiacomel commented on style.css
> +  height: 20px;
CSS já está ajustado!

2022-09-04 19:13 UTC, fernandagiacomel requested changes

2022-09-04 19:13 UTC, fernandagiacomel commented on home-nao-logada.html
> +        <header>
Só aqui Marlei, tem que tirar um dos header, a tag está duplicada, deve ficar só:
<body>
  <header>
    <p>Pet a vista</p>
    <button>Entrar</button>
  </header>
</body>

2022-09-04 19:25 UTC, marleicampos commented on home-nao-logada.html
> +        <header>
Ajustado

2022-09-04 19:26 UTC, alexa2me approved these changes

2022-09-04 19:47 UTC, fernandagiacomel approved these changes

2022-09-04 19:47 UTC, merged